language: go
go:
- 1.3
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
script:
- go test -v ./...
- $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: QU98O+EkVvqrGaHMwkrQ99R/Obuv0/pD7ihicye3URMzRimTxtmNVFk2nyzpVLnGSN+x8Alafz4APSaBelomFA6MvEJNTVO6URR/sTuNxUJaBf+IwJUiZQDHqFm/Qak11LUExakhh6B0w+itYfreNPOHpd/gPKphH/b6dDHz1q4=
