language: go
go:
- 1.3
- tip
install:
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go test -v ./...
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: QU98O+EkVvqrGaHMwkrQ99R/Obuv0/pD7ihicye3URMzRimTxtmNVFk2nyzpVLnGSN+x8Alafz4APSaBelomFA6MvEJNTVO6URR/sTuNxUJaBf+IwJUiZQDHqFm/Qak11LUExakhh6B0w+itYfreNPOHpd/gPKphH/b6dDHz1q4=
